repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

exclude: "^themes/blist-satre/(assets/css/site.css|assets/js/fuse\\.min\\.js|assets/js/search\\.js|exampleSite|i18n|CHANGELOG\\.md|README\\.md)"
